{
 "title": "Metrics Comparison",
 "tags": [ "Unified" ],
 "time": { "from": "now-30m", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(time),\n    host,\n    count()\nFROM fluentbit.latency_logs AS ll\nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '')\nGROUP BY\n    1,\n    2\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "QPS (INSERT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT                                                                                   \n    toStartOfMinute(time),                                                               \n    host,                                                                                \n    count()                                                                              \nFROM fluentbit.latency_logs AS ll                                                        \nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '') AND ( startsWith(ql.query, 'INSERT ') OR positionCaseInsensitive(ql.query, 'insert') )\nGROUP BY                                                                                 \n    1,                                                                                   \n    2                                                                                                                                                                              \nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "QPS (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(time),\n    host,\n    count()\nFROM fluentbit.latency_logs AS ll\nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '') AND ( startsWith(ql.query, 'SELECT ') OR positionCaseInsensitive(ql.query, 'select') OR positionCaseInsensitive(ql.query, 'find') )\nGROUP BY\n    1,\n    2\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    multiIf(startsWith(lower(query), 'select '), 'SELECT', startsWith(query, 'INSERT '), 'INSERT', 'OTHER'),\n    count()\nFROM fluentbit.query_logs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host,\n    avg(latency)\nFROM fluentbit.latency_logs AS lg\nINNER JOIN fluentbit.query_logs AS ql ON lg.correlation_id = ql.correlation_id\nWHERE ( startsWith(ql.query, 'INSERT ') OR positionCaseInsensitive(ql.query, 'insert') )\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Latency by query type",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT\n    multiIf(startsWith(ql.query, 'SELECT ') OR positionCaseInsensitive(ql.query, 'find'), 'SELECT', 'INSERT') as query_type,\n    host,\n    avg(latency)\nFROM fluentbit.latency_logs AS lg\nINNER JOIN fluentbit.query_logs AS ql ON lg.correlation_id = ql.correlation_id\nGROUP BY\n    1,\n    2"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs where host != '';"
    }
   ]
  },
  {
   "title": "Average latency (INSERT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs ll \ninner join fluentbit.query_logs ql on ll.correlation_id = ql.correlation_id where ll.host != '' \nand ( startsWith(ql.query, 'INSERT ') OR positionCaseInsensitive(ql.query, 'insert') );"
    }
   ]
  },
  {
   "title": "Average latency (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs ll \ninner join fluentbit.query_logs ql on ll.correlation_id = ql.correlation_id where ll.host != '' \nand ( startsWith(ql.query, 'SELECT ') OR positionCaseInsensitive(ql.query, 'select') OR positionCaseInsensitive(ql.query, 'find') );"
    }
   ]
  }
 ]
}