version: "3.8"
services:
  mysql-1:
    image: mysql:9.0.0
    # restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-chistadatademo2024}
      MYSQL_ROOT_HOST: "%"
#    volumes:
#      - type: bind
#        source: /mnt/disks/google-local-nvme-ssd-0/mysql
#        target: /var/lib/mysql
    ports:
      - "3306:3306"
    networks:
      - backend

  postgres-1:
    image: postgres:14.4
    command: >
      -c ssl=on
      -c ssl_cert_file=/var/lib/postgresql/server.crt
      -c ssl_key_file=/var/lib/postgresql/server.key
      -c shared_preload_libraries=pg_stat_statements
    ports:
      - "5432:5432"
      - "2345:2345"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-chistadatademo2024}
      PGDATA: /var/lib/postgresql/postgres-1/data/pgdata
    volumes:
      - source: pg_data
        target: /var/lib/postgresql/postgres-1/data
        type: volume
      - ./openssl/server.crt:/var/lib/postgresql/server.crt:ro
      - ./openssl/server.key:/var/lib/postgresql/server.key:ro
    networks:
      - backend

  postgres-exporter:
    image: quay.io/prometheuscommunity/postgres-exporter:latest
    command: >
      --config.file="/tmp/postgres_exporter.yml"
    ports:
      - "9187:9187"
    volumes:
      - ./postgres-exporter/postgres_exporter.yml:/tmp/postgres_exporter.yml
    environment:
      DATA_SOURCE_NAME: "postgresql://postgres:chistadatademo2024@postgres-1:5432/postgres?sslmode=disable"
    networks:
      - backend

volumes:
  pg_data:
networks:
  backend:
    driver: bridge
    driver_opts:
      com.docker.network.driver.mtu: 1400