host: 'localhost'
username: 'default'
password: 'password'
port: '9100'
ssl: 'False'
ca_cert: '/Users/midhundarvin/software/openssl/client.crt'
client_config: '/Users/midhundarvin/software/openssl/clickhouse-client-ssl.xml'
dataset_url: 'https://www.kaggle.com/datasets/midhundarvin/car-prices/download?datasetVersionNumber=1'
dataset_file_name: 'car_prices.csv.xz'
dataset_csv_name: 'car_prices.csv'
database: 'default'
table: 'car_prices'