host: 'localhost'
username: 'default'
password: '123456'

dataset_url: 'https://datasets.clickhouse.com/'
dataset_file_name: 'cell_towers.csv.xz'
dataset_csv_name: 'cell_towers.csv'
database: 'asabru_testing'
table: 'cell_towers'