host: 'localhost'
username: 'default'
password: ''
port: '9120'
ssl: 'True'
ca_cert: '/Users/midhundarvin/software/openssl/client.crt'
client_config: '/Users/midhundarvin/software/openssl/clickhouse-client-ssl.xml'
dataset_url: 'https://datasets.clickhouse.com/'
dataset_file_name: 'cell_towers.csv.xz'
dataset_csv_name: 'cell_towers.csv'
database: 'asabru_testing'
table: 'cell_towers'