host: 'localhost'
username: 'asabru'
password: '123456'
port: '9000'
ssl: 'False'
ca_cert: '/Users/midhundarvin/software/openssl/client.crt'
client_config: '/Users/midhundarvin/software/openssl/clickhouse-client-ssl.xml'
dataset_url: 'https://datasets.clickhouse.com/'
dataset_file_name: 'cell_towers.csv.xz'
dataset_csv_name: 'cell_towers.csv'
database: 'asabru_testing'
table: 'cell_towers'