host: '127.0.0.1'
username: 'asabru'
password: '123456'
port: '9160'
database: 'classicmodels'
table: 'employees'
ca_cert: '/Users/midhundarvin/certs/mysql/root-ca.pem'
ssl_cert: '/Users/midhundarvin/certs/mysql/client-cert.pem'
ssl_key: '/Users/midhundarvin/certs/mysql/client-key.pem'
ssl: 'True'