{
 "title": "Snowflake overview",
 "description": "Overview of Snowflake traffic and billing.",
 "tags": [ "snowflake-integration" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(snowflake_up{}, job)"
   },
   {
    "name": "instance",
    "label": "instance",
    "query": "label_values(snowflake_up{}, instance)"
   },
   {
    "name": "warehouse",
    "label": "Warehouse",
    "query": "label_values(snowflake_warehouse_used_compute_credits{name!=\"CLOUD_SERVICES_ONLY\"}, name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Warehouse activity",
   "type": "timeseries",
   "description": "Warehouse query activity for the warehouse selected by the Warehouse selector.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "snowflake_warehouse_executed_queries{instance=~\"$instance\", job=~\"$job\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Executed query load"
    },
    {
     "expr": "snowflake_warehouse_overloaded_queue_size{instance=~\"$instance\", job=~\"$job\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Overloaded queue load"
    },
    {
     "expr": "snowflake_warehouse_provisioning_queue_size{instance=~\"$instance\", job=~\"$job\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Provisioning queue load"
    },
    {
     "expr": "snowflake_warehouse_blocked_queries{instance=~\"$instance\", job=~\"$job\", name=~\"$warehouse\"}",
     "legendFormat": "{{instance}} - {{name}} - Blocked query load"
    }
   ]
  },
  {
   "title": "Account storage usage",
   "type": "timeseries",
   "description": "Data storage used for the account.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snowflake_storage_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Storage"
    },
    {
     "expr": "snowflake_stage_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Stage"
    },
    {
     "expr": "snowflake_failsafe_bytes{instance=~\"$instance\", job=~\"$job\"}",
     "legendFormat": "{{instance}} - Failsafe"
    }
   ]
  },
  {
   "title": "Login attempts",
   "type": "timeseries",
   "description": "Login attempt rate over the last 24 hours.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "logins/hr" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (snowflake_login_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Total"
    },
    {
     "expr": "sum by (job, instance) (snowflake_failed_login_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Failed"
    },
    {
     "expr": "sum by (job, instance) (snowflake_successful_login_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Successful"
    }
   ]
  },
  {
   "title": "Successful login attempts",
   "type": "gauge",
   "description": "Percentage of total login attempts that were successful.",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, instance) (snowflake_successful_login_rate{job=~\"$job\", instance=~\"$instance\"}) / sum by (job, instance) (snowflake_login_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Failed login attempts",
   "type": "gauge",
   "description": "Percentage of total login attempts that failed.",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (job, instance) (snowflake_failed_login_rate{job=~\"$job\", instance=~\"$instance\"}) / sum by (job, instance) (snowflake_login_rate{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Billing",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Average hourly credits used",
   "type": "barchart",
   "description": "Number of billing credits used by the account.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "sum by (job, instance) (snowflake_used_compute_credits{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Compute"
    },
    {
     "expr": "sum by (job, instance) (snowflake_used_cloud_services_credits{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "{{instance}} - Service"
    }
   ]
  },
  {
   "title": "Autoclustering credits used",
   "type": "timeseries",
   "description": "Credits billed for automatic reclustering.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_auto_clustering_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "{{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Top 5 service compute credits used",
   "type": "table",
   "description": "The top 5 services that have the highest compute credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_used_compute_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 service cloud service credits used",
   "type": "table",
   "description": "The top 5 services that have the highest compute credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_used_cloud_services_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 warehouse compute credits used",
   "type": "table",
   "description": "The top 5 warehouses that have the highest compute credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_warehouse_used_compute_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 warehouse cloud services credits used",
   "type": "table",
   "description": "The top 5 warehouses that have the highest services credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_warehouse_used_cloud_service_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 database autoclustering credits used",
   "type": "table",
   "description": "The top 5 databases that have the highest autoclustering credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "sum by (instance, job, database_name) (snowflake_auto_clustering_credits{job=~\"$job\", instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Top 5 table autoclustering credits used",
   "type": "table",
   "description": "The top 5 tables that have the highest autoclustering credit usages.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "credits/hr" } },
   "targets": [
    {
     "expr": "snowflake_auto_clustering_credits{job=~\"$job\", instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}