{
 "title": "Snowflake data ownership",
 "description": "A dashboard displaying metrics relating to data ownership.",
 "tags": [ "snowflake-integration" ],
 "time": { "from": "now-8h", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "prometheus_datasource", "label": "Data Source", "query": "prometheus" },
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(snowflake_up{}, job)"
   },
   {
    "name": "instance",
    "label": "Instance",
    "query": "label_values(snowflake_up{job=~\"$job\"}, instance)"
   },
   {
    "name": "database",
    "label": "Database",
    "query": "label_values(snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\"}, database_name)"
   },
   {
    "name": "schema",
    "label": "Schema",
    "query": "label_values(snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\"}, schema_name)"
   },
   {
    "name": "table",
    "label": "Table",
    "query": "label_values(snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\",  schema_name=~\"$schema\"}, table_name)"
   }
  ]
 },
 "panels": [
  {
   "title": "Active schema owned data",
   "type": "timeseries",
   "description": "Amount of active data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name) (snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Fail-safe schema owned data",
   "type": "timeseries",
   "description": "Amount of fail-safe data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name) (snowflake_table_failsafe_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Clone schema owned data",
   "type": "timeseries",
   "description": "Amount of clone data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name) (snowflake_table_clone_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Time travel schema owned data",
   "type": "timeseries",
   "description": "Amount of Time Travel data owned by the selected schema.",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name) (snowflake_table_time_travel_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}}"
    }
   ]
  },
  {
   "title": "Top 5 largest tables",
   "type": "table",
   "description": "The top 5 largest tables that belong to the selected schema.",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Table data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Active table owned data",
   "type": "timeseries",
   "description": "Amount of active data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name, table_name) (snowflake_table_active_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\", table_name=~\"$table\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Fail-safe table owned data",
   "type": "timeseries",
   "description": "Amount of fail-safe data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name, table_name) (snowflake_table_failsafe_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\", table_name=~\"$table\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Time travel table owned data",
   "type": "timeseries",
   "description": "Amount of Time Travel data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name, table_name) (snowflake_table_time_travel_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\", table_name=~\"$table\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  },
  {
   "title": "Clone table owned data",
   "type": "timeseries",
   "description": "Amount of clone data owned by the selected table.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "sum by (instance, database_name, schema_name, table_name) (snowflake_table_clone_bytes{job=~\"$job\", instance=~\"$instance\", database_name=~\"$database\", schema_name=~\"$schema\", table_name=~\"$table\"})",
     "legendFormat": "{{instance}} - {{database_name}} - {{schema_name}} - {{table_name}}"
    }
   ]
  }
 ]
}