{
 "title": "Query Metrics",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30m",
 "templating": {
  "list": [
   { "name": "Filters" }
  ]
 },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "rate(snowflake_query_count[$__rate_interval])",
     "legendFormat": "Query count"
    }
   ]
  },
  {
   "title": "Long duration queries",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by(query_text) (snowflake_query_elapsed_time)",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Top read queries by bytes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(query_text) (snowflake_query_bytes{query_type=\"SELECT\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Top insert queries by bytes",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "avg by(query_text) (snowflake_query_bytes{query_type=\"INSERT\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Top read queries by rows",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(query_text) (snowflake_query_rows{query_type=\"SELECT\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Top insert queries by rows",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(query_text) (snowflake_query_rows{query_type=\"INSERT\"})",
     "legendFormat": "{{query_text}}"
    }
   ]
  },
  {
   "title": "Top users",
   "type": "table",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "avg by(user_name) (snowflake_users_queries)",
     "legendFormat": "{{query_text}}"
    }
   ]
  }
 ]
}