{
 "title": "Metrics Comparison",
 "tags": [ "Unified" ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(time),\n    host,\n    count()\nFROM fluentbit.latency_logs AS ll\nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '')\nGROUP BY\n    1,\n    2\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "QPS (INSERT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT                                                                                   \n    toStartOfMinute(time),                                                               \n    host,                                                                                \n    count()                                                                              \nFROM fluentbit.latency_logs AS ll                                                        \nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '') AND startsWith(ql.query, 'INSERT ')\nGROUP BY                                                                                 \n    1,                                                                                   \n    2                                                                                                                                                                              \nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "QPS (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 10 },
   "targets": [
    {
     "rawSql": "SELECT\n    toStartOfMinute(time),\n    host,\n    count()\nFROM fluentbit.latency_logs AS ll\nINNER JOIN fluentbit.query_logs AS ql ON ll.correlation_id = ql.correlation_id\nWHERE (ll.host != '') AND startsWith(ql.query, 'SELECT ')\nGROUP BY\n    1,\n    2\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Query types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 21 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n    multiIf(startsWith(query, 'SELECT '), 'SELECT', 'INSERT'),\n    count()\nFROM fluentbit.query_logs\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT\n    host,\n    avg(latency)\nFROM fluentbit.latency_logs AS lg\nINNER JOIN fluentbit.query_logs AS ql ON lg.correlation_id = ql.correlation_id\nWHERE startsWith(ql.query, 'INSERT ')\nGROUP BY 1"
    }
   ]
  },
  {
   "title": "Latency by query type",
   "type": "table",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "SELECT\n    multiIf(startsWith(ql.query, 'SELECT '), 'SELECT', 'INSERT') as query_type,\n    host,\n    avg(latency)\nFROM fluentbit.latency_logs AS lg\nINNER JOIN fluentbit.query_logs AS ql ON lg.correlation_id = ql.correlation_id\nGROUP BY\n    1,\n    2"
    }
   ]
  },
  {
   "title": "Average latency",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs where host != '';"
    }
   ]
  },
  {
   "title": "Average latency (INSERT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs ll inner join fluentbit.query_logs ql on ll.correlation_id = ql.correlation_id where ll.host != '' and startsWith(ql.query, 'INSERT ');"
    }
   ]
  },
  {
   "title": "Average latency (SELECT)",
   "type": "timeseries",
   "gridPos": { "h": 11, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "rawSql": "select time, host, latency from fluentbit.latency_logs ll inner join fluentbit.query_logs ql on ll.correlation_id = ql.correlation_id where ll.host != '' and startsWith(ql.query, 'SELECT ');"
    }
   ]
  },
  {
   "title": "Credit usage by warehouses",
   "type": "barchart",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 51 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT warehouse_name,\n  SUM(credits_used_compute) AS credits_used\nFROM snowflake.account_usage.warehouse_metering_history\nWHERE start_time >= DATEADD(day, -10, CURRENT_TIMESTAMP())\nGROUP BY 1\nORDER BY 2 DESC;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Avg Credit Usage (hour by hour) last 10 days",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 60 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT DATE_PART('HOUR', start_time) AS start_hour,\n  warehouse_name,\n  AVG(credits_used_compute) AS credits_used_compute_avg\nFROM snowflake.account_usage.warehouse_metering_history\nWHERE start_time >= DATEADD(day, -10, CURRENT_TIMESTAMP())\n  AND warehouse_id > 0  -- Skip pseudo-VWs such as \"CLOUD_SERVICES_ONLY\"\nGROUP BY 1, 2\nORDER BY 1, 2;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Usage cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 70 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "select usage_date, sum(USAGE_IN_CURRENCY) from snowflake.organization_usage.USAGE_IN_CURRENCY_DAILY where usage_date >= DATEADD(day, -30, CURRENT_TIMESTAMP()) group by 1 order by 1;",
     "timeColumns": [ "time" ]
    }
   ]
  }
 ]
}