{
 "title": "clickhouse - visualizations",
 "time": { "from": "2024-02-28T08:56:01.602Z", "to": "2024-02-28T09:03:45.805Z" },
 "panels": [
  {
   "title": "Queries per second",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT date_trunc('second', timestamp) as seconds, COUNT(log) FROM \"fluentbit\".\"jsonlogs\"  WHERE ( timestamp >= $__fromTime AND timestamp <= $__toTime ) GROUP BY seconds  LIMIT 50"
    }
   ]
  },
  {
   "title": "Memory Consumption per Query",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT memory_usage ,query FROM system.query_log\nWHERE event_date in (today(), yesterday())\nORDER BY memory_usage DESC LIMIT 25;"
    }
   ]
  },
  {
   "title": "Query Duration in ms",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "rawSql": "SELECT query_duration_ms,query FROM system.query_log\nWHERE event_date in (today(), yesterday())\nORDER BY query_duration_ms DESC LIMIT 25;"
    }
   ]
  },
  {
   "title": "Top Write Queries",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT written_rows, written_bytes, query FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND written_rows > 0 AND query_kind = 'Insert'\nORDER BY written_rows DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Read Queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "rawSql": "SELECT query, read_bytes, read_rows FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Select'\nORDER BY read_rows DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top Users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT initial_user , count(query) as query_count FROM system.query_log\nWHERE event_date in (today(), yesterday()) GROUP BY initial_user \nORDER BY query_count DESC LIMIT 10;"
    }
   ]
  }
 ]
}