global:
  scrape_interval: 15s
  scrape_timeout: 10s
  evaluation_interval: 15s
alerting:
  alertmanagers:
    - static_configs:
        - targets: [ ]
      scheme: http
      timeout: 10s
      api_version: v1
scrape_configs:
  - job_name: 'fluentbit'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - localhost:9090
  - job_name: 'postgres'
    metrics_path: /metrics
    params:
      auth_module: [ foo ]
    static_configs:
      - targets: [ "postgres-exporter:9187" ]
  - job_name: 'clickhouse'
    honor_timestamps: true
    scrape_interval: 15s
    scrape_timeout: 10s
    metrics_path: /metrics
    scheme: http
    static_configs:
      - targets:
          - clickhouse-1:9363
  - job_name: snowflake
    scrape_interval: 30s
    scrape_timeout: 25s
    static_configs:
      - targets: [ "snowflake-exporter:9975" ]