{
 "title": "Master Dashboard",
 "tags": [ "Unified" ],
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Version", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Clickhouse",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "rawSql": "SELECT VERSION()" }
   ]
  },
  {
   "title": "Postgres",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "pg_static{release=\"\", instance=\"postgres-exporter:9187\"}",
     "legendFormat": "{{short_version}}"
    }
   ]
  },
  {
   "title": "Snowflake",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    { "queryText": "SELECT CURRENT_VERSION()", "timeColumns": [ "time" ] }
   ]
  },
  { "title": "Clickhouse", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "WITH queries_per_second AS\n    (\n        SELECT\n            event_time,\n            count() AS queries\n        FROM system.query_log\n        WHERE event_time > yesterday()\n        GROUP BY 1\n    )\nSELECT\n    toStartOfFiveMinutes(event_time),\n    avg(queries)\nFROM queries_per_second\nGROUP BY 1\nORDER BY 1 ASC"
    }
   ]
  },
  {
   "title": "Top insert queries by bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, avg(written_bytes) FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Insert'\ngroup by 1\nORDER BY 2 DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top insert queries by rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "SELECT query, avg(written_rows) FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Insert'\ngroup by 1\nORDER BY 2 DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top select queries by bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, avg(read_bytes) FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Select'\ngroup by 1\nORDER BY 2 DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top select queries by rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, avg(read_rows) FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Select'\ngroup by 1\nORDER BY 2 DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Top select queries by memory usage",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, sum(memory_usage) FROM system.query_log\nWHERE event_date in (today(), yesterday()) AND query_kind = 'Select' AND type = 'QueryFinish'\n    and user != 'monitoring-internal'\ngroup by 1\nORDER BY 2 DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Long duration queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
   "targets": [
    {
     "rawSql": "SELECT query, avg(query_duration_ms) FROM system.query_log\nWHERE event_date in (today(), yesterday())\ngroup by 1\nORDER BY 2 DESC LIMIT 25;"
    }
   ]
  },
  {
   "title": "Top users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 39 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "SELECT initial_user , count(query) as QUERIES FROM system.query_log WHERE event_date in (today(), yesterday()) GROUP BY initial_user ORDER BY QUERIES DESC LIMIT 10;"
    }
   ]
  },
  {
   "title": "Data compression",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 39 },
   "targets": [
    {
     "rawSql": "SELECT\n    database,\n    `table`,\n    formatReadableSize(sum(data_uncompressed_bytes)) AS uncompressed_size,\n    formatReadableSize(sum(data_compressed_bytes)) AS compressed_size,\n    sum(data_uncompressed_bytes) / sum(data_compressed_bytes) AS compression_ratio\nFROM system.parts\nWHERE database != 'system'\nGROUP BY\n    1,\n    2\nORDER BY 3 DESC"
    }
   ]
  },
  { "title": "Snowflake", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 47 } },
  {
   "title": "QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 48 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "WITH queries_per_second AS\n    (\n        select DATE_TRUNC('SECOND', start_time) as start_time, count(1) as queries from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) GROUP BY 1\n    )\nselect TIME_SLICE(start_time::TIMESTAMP_NTZ, 5, 'MINUTE', 'START')::TIMESTAMP_LTZ, avg(queries) FROM queries_per_second\nGROUP BY 1\nORDER BY 1 ASC;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Usage cost",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 56 },
   "fieldConfig": { "defaults": { "unit": "currencyUSD" } },
   "targets": [
    {
     "queryText": "select usage_date, sum(USAGE_IN_CURRENCY) from snowflake.organization_usage.USAGE_IN_CURRENCY_DAILY where usage_date >= DATEADD(day, -30, CURRENT_TIMESTAMP()) group by 1 order by 1;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Avg Credit Usage (hour by hour) last 10 days",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 17, "x": 0, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT DATE_PART('HOUR', start_time) AS start_hour,\n  warehouse_name,\n  AVG(credits_used_compute) AS credits_used_compute_avg\nFROM snowflake.account_usage.warehouse_metering_history\nWHERE start_time >= DATEADD(day, -10, CURRENT_TIMESTAMP())\n  AND warehouse_id > 0  -- Skip pseudo-VWs such as \"CLOUD_SERVICES_ONLY\"\nGROUP BY 1, 2\nORDER BY 1, 2;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Credit usage by warehouses",
   "type": "barchart",
   "gridPos": { "h": 10, "w": 7, "x": 17, "y": 66 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "SELECT warehouse_name,\n  SUM(credits_used_compute) AS credits_used\nFROM snowflake.account_usage.warehouse_metering_history\nWHERE start_time >= DATEADD(day, -10, CURRENT_TIMESTAMP())\nGROUP BY 1\nORDER BY 2 DESC;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Top insert queries by bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "select query_text, avg(bytes_written) from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) and query_text != '<redacted>' and query_type = 'INSERT' group by 1 order by 2 desc limit 25;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Top insert queries by rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 76 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select query_text, avg(rows_produced) from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) and query_text != '<redacted>' and query_type = 'INSERT' and ROWS_PRODUCED is not null group by 1 order by 2 desc limit 25;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Top select queries by bytes",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "queryText": "select query_text, avg(bytes_scanned) from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) and query_text != '<redacted>' and query_type = 'SELECT' group by 1 order by 2 desc limit 25;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Top select queries by rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 84 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "queryText": "select query_text, avg(rows_produced) from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) and query_text != '<redacted>' and query_type = 'SELECT' and ROWS_PRODUCED is not null group by 1 order by 2 desc limit 25;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Top users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "queryText": "select user_name, count(1) as queries from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) group by user_name order by 2 desc;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  {
   "title": "Long duration queries",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 92 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "queryText": "select query_text, avg(total_elapsed_time) from snowflake.account_usage.query_history where start_time > DATEADD('day', -1, current_timestamp) and query_text != '<redacted>' group by 1 order by 2 desc limit 25;",
     "timeColumns": [ "time" ]
    }
   ]
  },
  { "title": "Postgres", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 100 } },
  {
   "title": "Queries by execution time",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 101 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "rawSql": "select query, calls, total_exec_time, mean_exec_time from pg_stat_statements order by mean_exec_time desc limit 20;"
    }
   ]
  },
  {
   "title": "Top queries by rows",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 110 },
   "targets": [
    {
     "rawSql": "SELECT query, rows/calls AS avg_rows FROM pg_stat_statements ORDER BY avg_rows DESC LIMIT 25"
    }
   ]
  },
  {
   "title": "Top queries by bytes written",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 110 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, (8192 * shared_blks_written)/calls AS avg_bytes FROM pg_stat_statements WHERE shared_blks_written > 0 ORDER BY avg_bytes DESC LIMIT 25"
    }
   ]
  },
  {
   "title": "Top users",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "rawSql": "select pa.rolname, sum(calls) as queries from pg_stat_statements pss inner join pg_authid pa on pss.userid = pa.oid group by 1 order by 2 desc limit 25;"
    }
   ]
  },
  {
   "title": "Top queries by bytes read",
   "type": "table",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 118 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "rawSql": "SELECT query, (8192 * shared_blks_read)/calls AS avg_bytes FROM pg_stat_statements WHERE shared_blks_read > 0 ORDER BY avg_bytes DESC LIMIT 25"
    }
   ]
  }
 ]
}